figlet -f standard "X11 commands:"
echo ""
echo ""

echo "pcmanfm &                (for file explorer)"
echo "xterm                    (for GUI terminal)"
echo "mousepad &               (for text editor)"
echo "xeyes                    (moving eyes)"
echo "xclock                   (clock)"
echo "xclock -digital          (digital clock)"
echo "glxgears                 (moving gears)"
echo "firefox                  (firefox)"
echo "xterm -e [command]       (run command in separate window)"
echo "openbox &                (window manager)"
echo "xfce4-panel &            (pannel)"
echo "code-oss                 (Visual Studio Code)"
echo "gimp                     (GIMP)"
echo "vlc                      (VLC Media Player)"
echo "nvim [FILE]              (Neovim)"
echo "python3                  (Python Console)"
echo "python3 [FileName].py    (Compile Python File)"
echo "xfce4-panel &            (Top Bar)"
echo "figlet [TEXT]            (Ascii Title)"
echo "dbus-launch startxfce4   (Start XFCE)"
echo "lxappearance             (Tweaks - LXAppearance)
echo ""
echo ""
echo ""
echo "Enable X11:"
echo ""
echo "   termux-x11 :0 &"
echo "   export DISPLAY=:0"

echo ""
echo ""
